### PR TITLE
task3 Феничева

### PR DESCRIPTION
**Pull request by Alica032**
Компьютер несколько дней не работал, в понедельник не успела закоммитеть

### CODE REVIEW

**Comment by Alica032** [comment]
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
CPU: 0.875794+-0.0468881 s
CPU: 11.4182 GFlops
    Real iterations fraction: 56.2638%
Building kernels for GeForce GTX 1060 with Max-Q Design... 
Kernels compilation done in 0.018023 seconds
Device 1
	Program build log:



GPU: 0.0102798+-0.000396979 s
GPU: 972.778 GFlops
GPU vs CPU average results difference: 0.942446%

**Comment by Alica032** [comment]
CPU:     0.269394+-0.0032384 s
CPU:     371.204 millions/s
CPU OMP: 0.076236+-0.00623931 s
CPU OMP: 1311.72 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.0120073+-0.000222815 s
GPU: 8328.24 millions/s

**Comment by Alica032** [comment]
n=2 values in range: [-1023; 1023]
Max prefix sum: 0 on prefix [0; 0)
CPU: 5e-07+-5e-07 s
CPU: 4 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 4.95e-05+-5.1559e-06 s
GPU: 0.040404 millions/s
______________________________________________
n=4 values in range: [-1023; 1023]
Max prefix sum: 1014 on prefix [0; 2)
CPU: 0+-0 s
CPU: inf millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 5.41667e-05+-6.9861e-06 s
GPU: 0.0738462 millions/s
______________________________________________
n=8 values in range: [-1023; 1023]
Max prefix sum: 0 on prefix [0; 0)
CPU: 1.66667e-07+-3.72678e-07 s
CPU: 48 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 4.58333e-05+-2.03443e-06 s
GPU: 0.174545 millions/s
______________________________________________
n=16 values in range: [-1023; 1023]
Max prefix sum: 457 on prefix [0; 1)
CPU: 0+-0 s
CPU: inf millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 6.13333e-05+-1.59861e-06 s
GPU: 0.26087 millions/s
______________________________________________
n=32 values in range: [-1023; 1023]
Max prefix sum: 0 on prefix [0; 0)
CPU: 6.66667e-07+-4.71405e-07 s
CPU: 48 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 6.26667e-05+-1.15998e-05 s
GPU: 0.510638 millions/s
______________________________________________
n=64 values in range: [-1023; 1023]
Max prefix sum: 1170 on prefix [0; 17)
CPU: 8.33333e-07+-3.72678e-07 s
CPU: 76.8 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 4.25e-05+-1.89297e-06 s
GPU: 1.50588 millions/s
______________________________________________
n=128 values in range: [-1023; 1023]
Max prefix sum: 4773 on prefix [0; 124)
CPU: 8.33333e-07+-3.72678e-07 s
CPU: 153.6 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 5.01667e-05+-2.67187e-06 s
GPU: 2.5515 millions/s
______________________________________________
n=256 values in range: [-1023; 1023]
Max prefix sum: 7649 on prefix [0; 183)
CPU: 1.33333e-06+-4.71405e-07 s
CPU: 192 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.0003045+-1.97906e-06 s
GPU: 0.840722 millions/s
______________________________________________
n=512 values in range: [-1023; 1023]
Max prefix sum: 4170 on prefix [0; 52)
CPU: 2.66667e-06+-4.71405e-07 s
CPU: 192 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.000349+-3.11395e-05 s
GPU: 1.46705 millions/s
______________________________________________
n=1024 values in range: [-1023; 1023]
Max prefix sum: 14708 on prefix [0; 829)
CPU: 3.5e-06+-5e-07 s
CPU: 292.571 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.000235333+-6.2361e-06 s
GPU: 4.35127 millions/s
______________________________________________
n=2048 values in range: [-1023; 1023]
Max prefix sum: 22303 on prefix [0; 1779)
CPU: 7e-06+-0 s
CPU: 292.571 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.0002725+-3.63719e-05 s
GPU: 7.5156 millions/s
______________________________________________
n=4096 values in range: [-1023; 1023]
Max prefix sum: 4292 on prefix [0; 58)
CPU: 1.91667e-05+-3.72678e-07 s
CPU: 213.704 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.000234+-2.88675e-06 s
GPU: 17.5043 millions/s
______________________________________________
n=8192 values in range: [-1023; 1023]
Max prefix sum: 3297 on prefix [0; 470)
CPU: 2.51667e-05+-3.72678e-07 s
CPU: 325.51 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.000265167+-2.00617e-05 s
GPU: 30.8938 millions/s
______________________________________________
n=16384 values in range: [-1023; 1023]
Max prefix sum: 103982 on prefix [0; 10101)
CPU: 7.81667e-05+-1.57233e-06 s
CPU: 209.603 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.000263333+-3.09121e-06 s
GPU: 62.2177 millions/s
______________________________________________
n=32768 values in range: [-1023; 1023]
Max prefix sum: 75785 on prefix [0; 2074)
CPU: 0.000151167+-8.76388e-06 s
CPU: 216.767 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.000124+-3.41565e-06 s
GPU: 264.258 millions/s
______________________________________________
n=65536 values in range: [-1023; 1023]
Max prefix sum: 93500 on prefix [0; 61715)
CPU: 0.000199833+-3.72678e-07 s
CPU: 327.953 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.000185667+-5.82142e-06 s
GPU: 352.977 millions/s
______________________________________________
n=131072 values in range: [-1023; 1023]
Max prefix sum: 310443 on prefix [0; 102163)
CPU: 0.000424167+-1.39214e-05 s
CPU: 309.011 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.000323833+-2.38776e-05 s
GPU: 404.751 millions/s
______________________________________________
n=262144 values in range: [-1023; 1023]
Max prefix sum: 449686 on prefix [0; 211310)
CPU: 0.000818833+-1.24287e-05 s
CPU: 320.143 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.000809+-5.64358e-05 s
GPU: 324.035 millions/s
______________________________________________
n=524288 values in range: [-1023; 1023]
Max prefix sum: 18511 on prefix [0; 470827)
CPU: 0.00202783+-0.000151056 s
CPU: 258.546 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.0010825+-9.39415e-06 s
GPU: 484.331 millions/s
______________________________________________
n=1048576 values in range: [-1023; 1023]
Max prefix sum: 46638 on prefix [0; 12341)
CPU: 0.00480983+-9.66375e-05 s
CPU: 218.007 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.00196233+-2.45877e-05 s
GPU: 534.352 millions/s
______________________________________________
n=2097152 values in range: [-1023; 1023]
Max prefix sum: 1199401 on prefix [0; 1691780)
CPU: 0.00669717+-0.000365452 s
CPU: 313.14 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.00378183+-6.4318e-05 s
GPU: 554.533 millions/s
______________________________________________
n=4194304 values in range: [-511; 511]
Max prefix sum: 43576 on prefix [0; 3543860)
CPU: 0.012444+-9.50298e-05 s
CPU: 337.054 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.0071955+-8.08677e-05 s
GPU: 582.907 millions/s
______________________________________________
n=8388608 values in range: [-255; 255]
Max prefix sum: 262168 on prefix [0; 2631415)
CPU: 0.0246708+-0.000325504 s
CPU: 340.021 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.0138507+-0.0001434 s
GPU: 605.647 millions/s
______________________________________________
n=16777216 values in range: [-127; 127]
Max prefix sum: 79474 on prefix [0; 976207)
CPU: 0.0475272+-0.000496747 s
CPU: 353.003 millions/s
OpenCL devices:
  Device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Intel(R) Corporation. Total memory: 15999 Mb
Using device #0: GPU. GeForce GTX 1060 with Max-Q Design. Total memory: 6075 Mb
GPU: 0.0270632+-0.000131097 s
GPU: 619.928 millions/s

**Comment by PolarNick239** [comment]
В будущих заданиях пожалуйста делайте коммиты в рамках специально созданной ветки. Чтобы в вашем форки появились все коммиты и ветки которые я добавил - вам нужно сделать что-то [такое](https://help.github.com/articles/syncing-a-fork/).

По заданию: можете это задание доделать так как вы его уже начали, но как минимум вам нужно добавить в CMakeLists.txt все cpp файлы: https://github.com/GPGPUCourse2018/Tasks/blob/task3/CMakeLists.txt#L31-L39

**Comment by Alica032** [comment]
> В будущих заданиях пожалуйста делайте коммиты в рамках специально созданной ветки. Чтобы в вашем форки появились все коммиты и ветки которые я добавил - вам нужно сделать что-то [такое](https://help.github.com/articles/syncing-a-fork/) или [такое](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository).
> 
> По заданию: можете это задание доделать так как вы его уже начали, но как минимум вам нужно добавить в CMakeLists.txt все cpp файлы: https://github.com/GPGPUCourse2018/Tasks/blob/task3/CMakeLists.txt#L31-L39

Про pullреквесты ничего не поняла

какая последовательность действий?
сначала 
git clone https://github.com/Alica032/Tasks.git -b <branch>

дальше, когда я сделала commit и пыталась запушить, у меня какие-то ошибки были
поэтому я через сайт все файлы добавила

**Comment by PolarNick239** [comment]
Да, все правильно. Что именно пошло не так можно только по ошибкам понять. Либо попробуйте их вбить в переводчик, либо загуглите, либо скиньте их сюда.

**Comment by PolarNick239** [comment]
Все хорошо.

**Pull request closed without merging**
