### PR TITLE
Дмитрий Бойкий, HW 3

### PR DESCRIPTION
**Pull request by imbd**
### 3.2. 
<pre>
CPU:     0.531536+-0.0658049 s
CPU:     188.134 millions/s
CPU OMP: 0.180345+-0.00197123 s
CPU OMP: 554.492 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.0635875+-0.00154201 s
GPU: 1572.64 millions/s
<pre>

### CODE REVIEW

**Comment by imbd** [comment]
Доделывать буду, да, пока увы не успел.

**Comment by imbd** [comment]
Кажется, справился :)
Вот вывод по префиксам

<pre>
______________________________________________
n=2 values in range: [-1023; 1023]
Max prefix sum: 0 on prefix [0; 0)
CPU: 1e-06+-0 s
CPU: 2 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00166183+-9.23786e-05 s
GPU: 0.00120349 millions/s
______________________________________________
n=4 values in range: [-1023; 1023]
Max prefix sum: 1014 on prefix [0; 2)
CPU: 1e-06+-0 s
CPU: 4 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00153967+-6.14672e-05 s
GPU: 0.00259796 millions/s
______________________________________________
n=8 values in range: [-1023; 1023]
Max prefix sum: 0 on prefix [0; 0)
CPU: 1.16667e-06+-3.72678e-07 s
CPU: 6.85714 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.001623+-5.3864e-05 s
GPU: 0.00492914 millions/s
______________________________________________
n=16 values in range: [-1023; 1023]
Max prefix sum: 457 on prefix [0; 1)
CPU: 1.16667e-06+-3.72678e-07 s
CPU: 13.7143 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.001484+-8.53385e-05 s
GPU: 0.0107817 millions/s
______________________________________________
n=32 values in range: [-1023; 1023]
Max prefix sum: 0 on prefix [0; 0)
CPU: 1.16667e-06+-3.72678e-07 s
CPU: 27.4286 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.001636+-6.66208e-05 s
GPU: 0.0195599 millions/s
______________________________________________
n=64 values in range: [-1023; 1023]
Max prefix sum: 1170 on prefix [0; 17)
CPU: 1.5e-06+-5e-07 s
CPU: 42.6667 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00153717+-6.04522e-05 s
GPU: 0.041635 millions/s
______________________________________________
n=128 values in range: [-1023; 1023]
Max prefix sum: 4773 on prefix [0; 124)
CPU: 2e-06+-0 s
CPU: 64 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.001225+-8.85682e-05 s
GPU: 0.10449 millions/s
______________________________________________
n=256 values in range: [-1023; 1023]
Max prefix sum: 7649 on prefix [0; 183)
CPU: 2e-06+-0 s
CPU: 128 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00195967+-7.26812e-05 s
GPU: 0.130634 millions/s
______________________________________________
n=512 values in range: [-1023; 1023]
Max prefix sum: 4170 on prefix [0; 52)
CPU: 3e-06+-0 s
CPU: 170.667 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00180333+-0.000125719 s
GPU: 0.283919 millions/s
______________________________________________
n=1024 values in range: [-1023; 1023]
Max prefix sum: 14708 on prefix [0; 829)
CPU: 5.16667e-06+-3.72678e-07 s
CPU: 198.194 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00246583+-5.56579e-05 s
GPU: 0.415275 millions/s
______________________________________________
n=2048 values in range: [-1023; 1023]
Max prefix sum: 22303 on prefix [0; 1779)
CPU: 1e-05+-1.52753e-06 s
CPU: 204.8 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00234267+-0.000252707 s
GPU: 0.874217 millions/s
______________________________________________
n=4096 values in range: [-1023; 1023]
Max prefix sum: 4292 on prefix [0; 58)
CPU: 1.66667e-05+-4.71405e-07 s
CPU: 245.76 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00274483+-0.000117764 s
GPU: 1.49226 millions/s
______________________________________________
n=8192 values in range: [-1023; 1023]
Max prefix sum: 3297 on prefix [0; 470)
CPU: 3.2e-05+-0 s
CPU: 256 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00269717+-7.08953e-05 s
GPU: 3.03726 millions/s
______________________________________________
n=16384 values in range: [-1023; 1023]
Max prefix sum: 103982 on prefix [0; 10101)
CPU: 7.26667e-05+-1.22701e-05 s
CPU: 225.468 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00270933+-8.89076e-05 s
GPU: 6.04724 millions/s
______________________________________________
n=32768 values in range: [-1023; 1023]
Max prefix sum: 75785 on prefix [0; 2074)
CPU: 0.0001235+-3.3541e-06 s
CPU: 265.328 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.003269+-0.000155433 s
GPU: 10.0239 millions/s
______________________________________________
n=65536 values in range: [-1023; 1023]
Max prefix sum: 93500 on prefix [0; 61715)
CPU: 0.000254833+-1.21575e-05 s
CPU: 257.172 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00324+-0.00152259 s
GPU: 20.2272 millions/s
______________________________________________
n=131072 values in range: [-1023; 1023]
Max prefix sum: 310443 on prefix [0; 102163)
CPU: 0.000490333+-1.10554e-06 s
CPU: 267.312 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00361067+-7.35519e-05 s
GPU: 36.3013 millions/s
______________________________________________
n=262144 values in range: [-1023; 1023]
Max prefix sum: 449686 on prefix [0; 211310)
CPU: 0.001075+-4.16733e-05 s
CPU: 243.855 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00382433+-0.000106483 s
GPU: 68.5463 millions/s
______________________________________________
n=524288 values in range: [-1023; 1023]
Max prefix sum: 18511 on prefix [0; 470827)
CPU: 0.002001+-7.26705e-05 s
CPU: 262.013 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.004489+-0.0001237 s
GPU: 116.794 millions/s
______________________________________________
n=1048576 values in range: [-1023; 1023]
Max prefix sum: 46638 on prefix [0; 12341)
CPU: 0.00408617+-8.23942e-05 s
CPU: 256.616 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.0048435+-0.000163302 s
GPU: 216.491 millions/s
______________________________________________
n=2097152 values in range: [-1023; 1023]
Max prefix sum: 1199401 on prefix [0; 1691780)
CPU: 0.00835533+-0.000125556 s
CPU: 250.996 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.00718833+-0.000101797 s
GPU: 291.744 millions/s
______________________________________________
n=4194304 values in range: [-511; 511]
Max prefix sum: 43576 on prefix [0; 3543860)
CPU: 0.0164982+-0.00015947 s
CPU: 254.228 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.0117417+-0.00011943 s
GPU: 357.215 millions/s
______________________________________________
n=8388608 values in range: [-255; 255]
Max prefix sum: 262168 on prefix [0; 2631415)
CPU: 0.0333915+-0.000382002 s
CPU: 251.22 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.0197087+-0.000357175 s
GPU: 425.63 millions/s
______________________________________________
n=16777216 values in range: [-127; 127]
Max prefix sum: 79474 on prefix [0; 976207)
CPU: 0.0637455+-0.000560273 s
CPU: 263.191 millions/s
OpenCL devices:
  Device #0: CPU. Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz. Intel(R) Corporation. Total memory: 8088 Mb
  Device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
Using device #1: GPU. Intel(R) HD Graphics 520. Total memory: 3227 Mb
GPU: 0.0331443+-0.000261176 s
GPU: 506.187 millions/s
<pre>

**Comment by PolarNick239** [comment]
Все хорошо. Еще есть простая часть задания про фрактал Мандельброта, будете доделывать?

**Comment by imbd** [comment]
Ее уже, думаю, нет: возникли проблемы со сборкой и перешел на сортировки :)

**Comment by PolarNick239** [comment]
Хорошо.

На AMD R9 390X:
 - Суммирование выдает 35294 миллионов
 - Префиксная сумма выдает 1170 миллионов

**Pull request closed without merging**
