### PR TITLE
Task3 Лабутин Игорь

### PR DESCRIPTION
**Pull request by LabutinIgor**
sum:
CPU:     0.433791+-0.0131546 s
CPU:     230.526 millions/s
CPU OMP: 0.454673+-0.0287091 s
CPU OMP: 219.938 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.132385+-0.0022442 s
GPU: 755.372 millions/s

prefix_sum:
______________________________________________
n=2 values in range: [-1023; 1023]
Max prefix sum: 0 on prefix [0; 0)
CPU: 1e-06+-0 s
CPU: 2 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.00302083+-0.000239139 s
GPU: 0.000662069 millions/s
______________________________________________
n=4 values in range: [-1023; 1023]
Max prefix sum: 1014 on prefix [0; 2)
CPU: 1.16667e-06+-3.72678e-07 s
CPU: 3.42857 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.0034295+-0.000696665 s
GPU: 0.00116635 millions/s
______________________________________________
n=8 values in range: [-1023; 1023]
Max prefix sum: 0 on prefix [0; 0)
CPU: 1e-06+-0 s
CPU: 8 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.00253417+-0.000108076 s
GPU: 0.00315686 millions/s
______________________________________________
n=16 values in range: [-1023; 1023]
Max prefix sum: 457 on prefix [0; 1)
CPU: 1.16667e-06+-3.72678e-07 s
CPU: 13.7143 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.002295+-9.38723e-05 s
GPU: 0.00697168 millions/s
______________________________________________
n=32 values in range: [-1023; 1023]
Max prefix sum: 0 on prefix [0; 0)
CPU: 1e-06+-0 s
CPU: 32 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.002547+-4.27941e-05 s
GPU: 0.0125638 millions/s
______________________________________________
n=64 values in range: [-1023; 1023]
Max prefix sum: 1170 on prefix [0; 17)
CPU: 2e-06+-0 s
CPU: 32 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.001899+-0.000300432 s
GPU: 0.0337019 millions/s
______________________________________________
n=128 values in range: [-1023; 1023]
Max prefix sum: 4773 on prefix [0; 124)
CPU: 2.33333e-06+-4.71405e-07 s
CPU: 54.8571 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.0024995+-7.10041e-05 s
GPU: 0.0512102 millions/s
______________________________________________
n=256 values in range: [-1023; 1023]
Max prefix sum: 7649 on prefix [0; 183)
CPU: 3.83333e-06+-3.72678e-07 s
CPU: 66.7826 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.0044065+-0.000452153 s
GPU: 0.058096 millions/s
______________________________________________
n=512 values in range: [-1023; 1023]
Max prefix sum: 4170 on prefix [0; 52)
CPU: 4e-06+-0 s
CPU: 128 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.00498517+-0.000459361 s
GPU: 0.102705 millions/s
______________________________________________
n=1024 values in range: [-1023; 1023]
Max prefix sum: 14708 on prefix [0; 829)
CPU: 6e-06+-1.1547e-06 s
CPU: 170.667 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.00368333+-0.000395663 s
GPU: 0.278009 millions/s
______________________________________________
n=2048 values in range: [-1023; 1023]
Max prefix sum: 22303 on prefix [0; 1779)
CPU: 9.66667e-06+-1.49071e-06 s
CPU: 211.862 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.00479867+-0.000713156 s
GPU: 0.426785 millions/s
______________________________________________
n=4096 values in range: [-1023; 1023]
Max prefix sum: 4292 on prefix [0; 58)
CPU: 2.45e-05+-5e-07 s
CPU: 167.184 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.004608+-0.000788342 s
GPU: 0.888889 millions/s
______________________________________________
n=8192 values in range: [-1023; 1023]
Max prefix sum: 3297 on prefix [0; 470)
CPU: 3.75e-05+-5.34634e-06 s
CPU: 218.453 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.00518333+-0.000867001 s
GPU: 1.58045 millions/s
______________________________________________
n=16384 values in range: [-1023; 1023]
Max prefix sum: 103982 on prefix [0; 10101)
CPU: 5.18333e-05+-6.87184e-07 s
CPU: 316.09 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.00460383+-0.000515122 s
GPU: 3.55877 millions/s
______________________________________________
n=32768 values in range: [-1023; 1023]
Max prefix sum: 75785 on prefix [0; 2074)
CPU: 9.8e-05+-0 s
CPU: 334.367 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.0087485+-0.00120103 s
GPU: 3.74556 millions/s
______________________________________________
n=65536 values in range: [-1023; 1023]
Max prefix sum: 93500 on prefix [0; 61715)
CPU: 0.000241167+-2.18435e-05 s
CPU: 271.746 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.00802217+-0.000984491 s
GPU: 8.16936 millions/s
______________________________________________
n=131072 values in range: [-1023; 1023]
Max prefix sum: 310443 on prefix [0; 102163)
CPU: 0.000392833+-6.87184e-07 s
CPU: 333.658 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.00833433+-0.00091389 s
GPU: 15.7268 millions/s
______________________________________________
n=262144 values in range: [-1023; 1023]
Max prefix sum: 449686 on prefix [0; 211310)
CPU: 0.000808833+-2.76069e-05 s
CPU: 324.101 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.00894567+-0.000121489 s
GPU: 29.304 millions/s
______________________________________________
n=524288 values in range: [-1023; 1023]
Max prefix sum: 18511 on prefix [0; 470827)
CPU: 0.00155217+-1.17674e-05 s
CPU: 337.778 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.0116317+-0.000885024 s
GPU: 45.0742 millions/s
______________________________________________
n=1048576 values in range: [-1023; 1023]
Max prefix sum: 46638 on prefix [0; 12341)
CPU: 0.00319+-6.91062e-05 s
CPU: 328.707 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.015051+-0.000155656 s
GPU: 69.6682 millions/s
______________________________________________
n=2097152 values in range: [-1023; 1023]
Max prefix sum: 1199401 on prefix [0; 1691780)
CPU: 0.00698283+-0.000142662 s
CPU: 300.33 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.0216485+-0.00259654 s
GPU: 96.8729 millions/s
______________________________________________
n=4194304 values in range: [-511; 511]
Max prefix sum: 43576 on prefix [0; 3543860)
CPU: 0.0136893+-0.000335534 s
CPU: 306.392 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.038773+-0.000393103 s
GPU: 108.176 millions/s
______________________________________________
n=8388608 values in range: [-255; 255]
Max prefix sum: 262168 on prefix [0; 2631415)
CPU: 0.0285528+-0.000752564 s
CPU: 293.792 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.0506683+-0.00459999 s
GPU: 165.559 millions/s
______________________________________________
n=16777216 values in range: [-127; 127]
Max prefix sum: 79474 on prefix [0; 976207)
CPU: 0.0565843+-0.00120165 s
CPU: 296.499 millions/s
OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
GPU: 0.0699075+-0.0034931 s
GPU: 239.992 millions/s

### CODE REVIEW

**Comment by LabutinIgor** [comment]
Мандельброта пока нет. Там не собирается libimages, возможно потому что mac...

/Users/igorl/Documents/au_ms/gpu/Tasks/libs/images/libimages/images.cpp:344:16: error: explicit instantiation of 'images::Image' must occur in namespace 'images'
template class Image<unsigned char>;
               ^
/Users/igorl/Documents/au_ms/gpu/Tasks/libs/images/libimages/images.h:65:11: note: explicit instantiation refers here
    class Image {
          ^
/Users/igorl/Documents/au_ms/gpu/Tasks/libs/images/libimages/images.cpp:345:16: error: explicit instantiation of 'images::Image' must occur in namespace 'images'
template class Image<unsigned short>;
               ^
/Users/igorl/Documents/au_ms/gpu/Tasks/libs/images/libimages/images.h:65:11: note: explicit instantiation refers here
    class Image {
          ^
/Users/igorl/Documents/au_ms/gpu/Tasks/libs/images/libimages/images.cpp:346:16: error: explicit instantiation of 'images::Image' must occur in namespace 'images'
template class Image<float>;
               ^
/Users/igorl/Documents/au_ms/gpu/Tasks/libs/images/libimages/images.h:65:11: note: explicit instantiation refers here
    class Image {

**Comment by LabutinIgor** [comment]
> Я извиняюсь, это некорректный код и Clang прав. А я и GCC/MinGW/MSVC упустили это. ([см.](http://docwiki.embarcadero.com/RADStudio/Tokyo/en/Explicit_instantiation_of_%27namespace::templated_class%27_must_occur_in_namespace_%27namespace%27_(C%2B%2B)))
> 
> Такое локальное изменение вам помогает? [f8388e1](https://github.com/GPGPUCourse2018/Tasks/commit/f8388e16dc4e6380495b3a573d504e5b7a5969e0)

Да, но теперь при сохранении проблема.

[CImg] *** CImgIOException *** [instance(2048,2048,1,3,0x112228000,non-shared)] CImg<unsigned char>::save_other(): Failed to save file 'mandelbrot_cpu.png'. Format is not natively supported, and no external commands succeeded.
libc++abi.dylib: terminating with uncaught exception of type cimg_library::CImgIOException: [instance(2048,2048,1,3,0x112228000,non-shared)] CImg<unsigned char>::save_other(): Failed to save file 'mandelbrot_cpu.png'. Format is not natively supported, and no external commands succeeded.

**Comment by PolarNick239** [comment]
Попробуйте установить Graphics Magick - например [через brew](https://stackoverflow.com/a/17846596/1549330).

**Comment by LabutinIgor** [comment]
Спасибо, доделал.

OpenCL devices:
  Device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
  Device #1: CPU. Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz. Intel. Total memory: 8192 Mb
Using device #0: GPU. HD Graphics 5000. Total memory: 1536 Mb
CPU: 5.40644+-0.0809945 s
CPU: 1.84965 GFlops
    Real iterations fraction: 56.2638%
GPU: 0.04073+-0.00290381 s
GPU: 245.519 GFlops
    Real iterations fraction: 56.2657%
GPU vs CPU average results difference: 0.942446%

**Comment by PolarNick239** [comment]
Все хорошо.

**Pull request closed without merging**
